# Generated by Django 6.0 on 2025-12-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_post_comment_postimage_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
