# Generated by Django 6.0 on 2025-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_post_button_text_post_button_url_post_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='localBody',
            field=models.CharField(max_length=255),
        ),
    ]
