# Generated by Django 6.0 on 2025-12-23 03:38

from django.db import migrations
import uuid


def populate_user_ids(apps, schema_editor):
    User = apps.get_model('basic', 'User')
    for user in User.objects.filter(userId__isnull=True):
        user.userId = uuid.uuid4()
        user.save()


def reverse_populate(apps, schema_editor):
    # No need to reverse, just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_user_userid_alter_user_localbody'),
    ]

    operations = [
        migrations.RunPython(populate_user_ids, reverse_populate),
    ]
