# Generated by Django 6.0 on 2025-12-23 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_populate_user_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
