# Generated by Django 6.0 on 2025-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_postimage_image_url_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
