# Generated by Django 6.0 on 2025-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
