# Generated by Django 6.0 on 2026-01-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_add_image_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
